package main

import (
	"fmt"
	"strings"
	"sync/atomic"
	"syscall"
	"unsafe"
)

const (
	windowClassName = "DshRemoteTrayWindow"

	// The one thing this program watches the launcher's output for. The banner
	// prints it when the console has no administrator yet
	// (packages/launcher/src/banner.ts), and that is the only state the user has
	// to be told about before anything works.
	adminMissingMarker = "还没有管理员账号"
)

// Private messages. wmTrayCallback is what Shell_NotifyIcon posts back; the
// other two exist so that work finished on a worker goroutine is turned into UI
// on the thread that owns the window.
const (
	wmTrayCallback = wmApp + 1
	wmStateChanged = wmApp + 2
	wmSetupNotice  = wmApp + 3
)

// Menu command identifiers. TrackPopupMenu returns these directly
// (TPM_RETURNCMD), which is why there is no WM_COMMAND handling below.
const (
	idOpenConsole uintptr = iota + 1
	idOpenDsh
	idStart
	idStop
	idRestart
	idLog
	idAutostart
	idExit
)

type application struct {
	hwnd       syscall.Handle
	icon       syscall.Handle
	iconOwned  bool
	executable string
	root       string
	settings   settings
	log        *rotatingLog
	stack      *stack
	// The setup balloon is shown once per run: the launcher reprints the banner
	// on every restart, and a notification per restart is nagging, not helping.
	setupNoticeShown atomic.Bool
}

var (
	app *application
	// Explorer posts this when it restarts, and every tray icon has to be added
	// again; without it the icon silently disappears for the rest of the session.
	taskbarCreatedMessage uint32
	// Kept alive for the lifetime of the process: Windows calls it long after
	// the function that registered it returned.
	wndProcCallback = syscall.NewCallback(wndProc)
)

func stateLabel(state stackState) string {
	switch state {
	case stackStarting:
		return "正在启动"
	case stackRunning:
		return "运行中"
	case stackStopping:
		return "正在停止"
	default:
		return "已停止"
	}
}

func wndProc(hwnd syscall.Handle, message uint32, wParam uintptr, lParam uintptr) uintptr {
	switch message {
	case wmTrayCallback:
		// Version 3 packing: the mouse message is in the low word of lParam.
		switch uint32(lParam & 0xffff) {
		case wmRButtonUp, wmContextMenu:
			app.showMenu()
		case wmLButtonDblClk:
			app.openConsole()
		case ninBalloonUserClick:
			app.openConsole()
		}
		return 0
	case wmStateChanged:
		app.updateTooltip()
		return 0
	case wmSetupNotice:
		app.showSetupBalloon()
		return 0
	case wmClose:
		procDestroyWindow.Call(uintptr(hwnd))
		return 0
	case wmDestroy:
		procPostQuitMessage.Call(0)
		return 0
	}
	if taskbarCreatedMessage != 0 && message == taskbarCreatedMessage {
		app.addIcon()
		return 0
	}
	result, _, _ := procDefWindowProcW.Call(uintptr(hwnd), uintptr(message), wParam, lParam)
	return result
}

// createWindow makes the hidden window every tray icon needs: Shell_NotifyIcon
// delivers its clicks as window messages, and TrackPopupMenu needs a window it
// can make foreground or the menu never closes again.
func createWindow() (syscall.Handle, error) {
	instance, err := moduleHandle()
	if err != nil {
		return 0, err
	}
	className := utf16Ptr(windowClassName)
	class := wndClassEx{
		lpfnWndProc:   wndProcCallback,
		hInstance:     instance,
		lpszClassName: className,
	}
	class.cbSize = uint32(unsafe.Sizeof(class))
	atom, _, err := procRegisterClassExW.Call(uintptr(unsafe.Pointer(&class)))
	if atom == 0 {
		return 0, fmt.Errorf("RegisterClassExW 失败：%w", err)
	}
	hwnd, _, err := procCreateWindowExW.Call(
		0,
		uintptr(unsafe.Pointer(className)),
		uintptr(unsafe.Pointer(utf16Ptr(appName))),
		0, 0, 0, 0, 0, 0, 0,
		uintptr(instance),
		0,
	)
	if hwnd == 0 {
		return 0, fmt.Errorf("CreateWindowExW 失败：%w", err)
	}
	return syscall.Handle(hwnd), nil
}

// loadTrayIcon takes the icon out of this executable's own resources
// (packaging/win-launcher/rsrc_windows_amd64.syso, generated by
// packaging/make-icons.mjs) and falls back to the stock application icon:
// a program with no icon at all would cost the user the only handle they have
// on it.
//
// The size asked for is SM_CXSMICON rather than LR_DEFAULTSIZE's 32x32, and the
// resource carries 16/20/24/32/48/... so LoadImage picks a real image instead of
// squashing one. The process is per-monitor DPI aware (see the manifest in the
// same resource file), so that metric already comes back scaled — 24 at 150%.
func loadTrayIcon() (syscall.Handle, bool) {
	width, _, _ := procGetSystemMetrics.Call(smCXSmIcon)
	height, _, _ := procGetSystemMetrics.Call(smCYSmIcon)
	if instance, err := moduleHandle(); err == nil {
		handle, _, _ := procLoadImageW.Call(
			uintptr(instance),
			appIconResourceID,
			imageIcon,
			width,
			height,
			0,
		)
		if handle != 0 {
			return syscall.Handle(handle), true
		}
	}
	stock, _, _ := procLoadIconW.Call(0, idiApplication)
	return syscall.Handle(stock), false
}

func (a *application) baseIconData() notifyIconData {
	data := notifyIconData{
		hWnd:             a.hwnd,
		uID:              1,
		uCallbackMessage: wmTrayCallback,
		hIcon:            a.icon,
	}
	data.cbSize = uint32(unsafe.Sizeof(data))
	return data
}

func (a *application) tooltip() string {
	return fmt.Sprintf("dsh-remote（%s）— 控制台 %s", stateLabel(a.stack.currentState()), a.settings.consoleURL())
}

func (a *application) addIcon() {
	data := a.baseIconData()
	data.uFlags = nifMessage | nifIcon | nifTip
	setUTF16(data.szTip[:], a.tooltip())
	procShellNotifyIconW.Call(uintptr(nimAdd), uintptr(unsafe.Pointer(&data)))
	// Asking for version 3 is what makes a balloon click come back as
	// NIN_BALLOONUSERCLICK instead of being swallowed.
	version := a.baseIconData()
	version.uVersion = notifyIconVersion
	procShellNotifyIconW.Call(uintptr(nimSetVersion), uintptr(unsafe.Pointer(&version)))
}

func (a *application) removeIcon() {
	data := a.baseIconData()
	procShellNotifyIconW.Call(uintptr(nimDelete), uintptr(unsafe.Pointer(&data)))
	if a.iconOwned && a.icon != 0 {
		procDestroyIcon.Call(uintptr(a.icon))
	}
}

func (a *application) updateTooltip() {
	data := a.baseIconData()
	data.uFlags = nifTip
	setUTF16(data.szTip[:], a.tooltip())
	procShellNotifyIconW.Call(uintptr(nimModify), uintptr(unsafe.Pointer(&data)))
}

// showSetupBalloon is the one notification this program raises by itself. It
// says what is missing and offers the page; it does not open it (D6) — the user
// has to click.
func (a *application) showSetupBalloon() {
	data := a.baseIconData()
	data.uFlags = nifInfo
	data.dwInfoFlags = niifInfo
	setUTF16(data.szInfoTitle[:], "dsh-remote 还没有设置完成")
	setUTF16(data.szInfo[:], "还没有管理员账号，控制台暂时不能登录。点这条通知，在本机浏览器里完成设置。")
	procShellNotifyIconW.Call(uintptr(nimModify), uintptr(unsafe.Pointer(&data)))
}

func (a *application) onChildLine(line string) {
	if !strings.Contains(line, adminMissingMarker) {
		return
	}
	if a.setupNoticeShown.Swap(true) {
		return
	}
	// Posted rather than called: this runs on the goroutine draining the child's
	// output, and every shell call belongs to the thread owning the window.
	procPostMessageW.Call(uintptr(a.hwnd), uintptr(wmSetupNotice), 0, 0)
}

func (a *application) onStateChange() {
	procPostMessageW.Call(uintptr(a.hwnd), uintptr(wmStateChanged), 0, 0)
}

func appendItem(menu uintptr, id uintptr, label string, enabled bool) {
	flags := mfString
	if !enabled {
		flags |= mfGrayed
	}
	procAppendMenuW.Call(menu, flags, id, uintptr(unsafe.Pointer(utf16Ptr(label))))
}

func appendCheckItem(menu uintptr, id uintptr, label string, checked bool) {
	flags := mfString
	if checked {
		flags |= mfChecked
	}
	procAppendMenuW.Call(menu, flags, id, uintptr(unsafe.Pointer(utf16Ptr(label))))
}

func appendSeparator(menu uintptr) {
	procAppendMenuW.Call(menu, mfSeparator, 0, 0)
}

// showMenu builds the menu from scratch on every right-click, so what it shows
// — which of 启动 / 停止 / 重启 is available, whether autostart is on — is read
// at the moment it is drawn rather than remembered.
//
// 初始化、重置密码、重置 TOTP are deliberately absent: they all need text input,
// Win32 has no built-in input dialog, and the relay already does all three in
// the browser. 打开控制台 is the way there.
func (a *application) showMenu() {
	menu, _, _ := procCreatePopupMenu.Call()
	if menu == 0 {
		return
	}
	defer procDestroyMenu.Call(menu)

	state := a.stack.currentState()
	appendItem(menu, idOpenConsole, "打开控制台", true)
	appendItem(menu, idOpenDsh, "打开 dsh 界面", true)
	appendSeparator(menu)
	appendItem(menu, idStart, "启动", state == stackStopped)
	appendItem(menu, idStop, "停止", state == stackRunning || state == stackStarting)
	appendItem(menu, idRestart, "重启", state == stackRunning)
	appendSeparator(menu)
	appendItem(menu, idLog, "查看日志", true)
	appendCheckItem(menu, idAutostart, "开机自启动", autostartEnabled())
	appendSeparator(menu)
	appendItem(menu, idExit, "退出", true)
	// Bold, and what a double-click on the icon does.
	procSetMenuDefaultItem.Call(menu, idOpenConsole, 0)

	// Without this the menu stays on screen after a click elsewhere: Windows
	// only dismisses a tracked menu owned by the foreground window.
	procSetForegroundWindow.Call(uintptr(a.hwnd))
	var cursor point
	procGetCursorPos.Call(uintptr(unsafe.Pointer(&cursor)))
	chosen, _, _ := procTrackPopupMenu.Call(
		menu,
		tpmLeftAlign|tpmBottomAlign|tpmRightButton|tpmReturnCmd|tpmNonNotify,
		uintptr(cursor.x),
		uintptr(cursor.y),
		0,
		uintptr(a.hwnd),
		0,
	)
	// The documented companion to SetForegroundWindow above; it lets the menu
	// tear itself down properly.
	procPostMessageW.Call(uintptr(a.hwnd), uintptr(wmNull), 0, 0)
	a.invoke(chosen)
}

// invoke runs a menu command. Anything that waits on a process is handed to a
// goroutine: this runs inside the message loop, and a blocked loop is a frozen
// icon and a menu that will not open again.
func (a *application) invoke(command uintptr) {
	switch command {
	case idOpenConsole:
		a.openConsole()
	case idOpenDsh:
		a.open(a.settings.dshURL())
	case idStart:
		a.stack.start()
	case idStop:
		go a.stack.stop()
	case idRestart:
		go a.stack.restart()
	case idLog:
		a.openLog()
	case idAutostart:
		a.toggleAutostart()
	case idExit:
		go a.quit()
	}
}

func (a *application) openConsole() {
	a.open(a.settings.consoleURL())
}

func (a *application) open(target string) {
	if err := shellOpen(target); err != nil {
		a.log.printf("打开 %s 失败：%v", target, err)
		messageBox("打不开 "+target+"：\n\n"+err.Error(), appName, mbIconError)
	}
}

func (a *application) openLog() {
	path := a.settings.logPath()
	if err := shellOpen(path); err == nil {
		return
	}
	// .log has no association on a stock Windows, and the "open with" dialog is
	// a worse answer than simply showing the file.
	if err := shellOpenWith("notepad.exe", path); err != nil {
		messageBox("打不开日志文件：\n\n"+path+"\n\n"+err.Error(), appName, mbIconError)
	}
}

func (a *application) toggleAutostart() {
	enabled := autostartEnabled()
	if err := setAutostart(a.executable, !enabled); err != nil {
		a.log.printf("修改开机自启动失败：%v", err)
		messageBox("改不了开机自启动：\n\n"+err.Error(), appName, mbIconError)
		return
	}
	if enabled {
		a.log.printf("已关闭开机自启动")
		return
	}
	a.log.printf("已开启开机自启动：%s", a.executable)
}

// quit stops the children first: the icon must not disappear while dsh is still
// running, or the user has no way left to stop it.
func (a *application) quit() {
	a.stack.stop()
	procPostMessageW.Call(uintptr(a.hwnd), uintptr(wmClose), 0, 0)
}

func runMessageLoop() {
	var message msg
	for {
		result, _, _ := procGetMessageW.Call(uintptr(unsafe.Pointer(&message)), 0, 0, 0)
		// 0 is WM_QUIT, -1 is an error; both mean this loop is over.
		if result == 0 || int32(result) == -1 {
			return
		}
		procTranslateMessage.Call(uintptr(unsafe.Pointer(&message)))
		procDispatchMessageW.Call(uintptr(unsafe.Pointer(&message)))
	}
}
